# Generated by Django 2.2.7 on 2019-12-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('admission_date', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('C', 'Cat'), ('D', 'Dog')], max_length=1)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
